runtime: python37
api_version: 1
service: estimated_charges

builtins:
- deferred: on

handlers:
- url: /
  script: main.app
- url: /_ah/task/estimated_charges
  script: main.app

libraries:
- name: numpy
  version: "1.9.0"

env_variables:
  METRIC_NAME: "estimated_charges"
  PROJECT_ID: "YOUR_PROJECT_ID"
  GCP_MONTH_BILLING_TABLE: "TABLE_ID in format: dataset_name.table_name"
